<sect1 id="zend.exception.using">

    <title>Использование исключений</title>

    <para>
        Все исключения, бросаемые классами Zend Framework, должны быть
        наследниками основного класса Zend_Exception.
    </para>

    <example id="zend.exception.using.example">
        <title>Пример отлова исключения</title>
        <programlisting language="php"><![CDATA[
try {
    Zend_Loader::loadClass('nonexistantclass');
} catch (Zend_Exception $e) {
    echo "Caught exception: " . get_class($e) . "\n";
    echo "Message: " . $e->getMessage() . "\n";
    // other code to recover from the failure.
}
]]>
        </programlisting>
    </example>

    <para>
        Более детальную информацию о том, какие методы могут бросать исключения,
        условия, при которых бросаются исключения, и о том, какие классы
        исключений наследуют от Zend_Exception, можно найти в документации по
        соответсвующей компоненте Zend Framework.
    </para>

</sect1>
<!--
vim:se ts=4 sw=4 et:
-->
