<?xml version="1.0" encoding="UTF-8"?>
<!-- Reviewed: no -->
<!-- EN-Revision: 21586 -->
<sect1 id="zend.exception.previous">
    <title>Previous Exceptions (前の例外)</title>

    <para>
        Zend Framework 1.10 から、 <classname>Zend_Exception</classname> は <acronym>PHP</acronym> 5.3 がサポートする
        previous exceptions (前の例外)を実装しています。単に配置するだけで、 <methodname>catch</methodname>
        節に、元の例外を参照する新しい例外を投げることができ、デバッグの際の追加コンテキスト
        の提供を助けます。 Zend Framework にてこのサポートを提供することによって、あなたのコードは
        <acronym>PHP</acronym> 5.3 と互換性のあるものへと転換するでしょう。
    </para>

    <para>
        Previous exceptions は例外のコンストラクタへの第 3 引数として示されます。
    </para>

    <example id="zend.exception.previous.example">
        <title>Previous exceptions (前の例外)</title>

        <programlisting language="php"><![CDATA[
try {
    $db->query($sql);
} catch (Zend_Db_Statement_Exception $e) {
    if ($e->getPrevious()) {
        echo '[' . get_class($e)
            . '] has the previous exception of ['
            . get_class($e->getPrevious())
            . ']' . PHP_EOL;
    } else {
        echo '[' . get_class($e)
            . '] does not have a previous exception'
            . PHP_EOL;
    }

    echo $e;
    // 可能な場合、最初の例外で始まる例外を全て表示します。
}
]]></programlisting>
    </example>
</sect1>
<!--
vim:se ts=4 sw=4 et:
-->
